In [6]:
%pip install pandas

Collecting pandas
  Downloading pandas-3.0.6-cp314-cp314-win_amd64.whl.metadata (19 kB)
Requirement already satisfied: numpy>=2.3.3 in d:\walid\formation data engineer openclassromm\chapitre 11\puls-events-rag\.venv\lib\site-packages (from pandas) (2.5.4)
Requirement already satisfied: python-dateutil>=2.8.2 in d:\walid\formation data engineer openclassromm\chapitre 11\puls-events-rag\.venv\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in d:\walid\formation data engineer openclassromm\chapitre 11\puls-events-rag\.venv\lib\site-packages (from pandas) (2026.5)
Requirement already satisfied: six>=1.5 in d:\walid\formation data engineer openclassromm\chapitre 11\puls-events-rag\.venv\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Downloading pandas-3.0.6-cp314-cp314-win_amd64.whl (9.8 MB)
   ---------------------------------------- 0.0/9.8 MB ? eta -:--:--
   - -------------------------------------- 0.3/9.8 MB ? eta -:--:--
   -- ------------------------------------- 0.5/9.8 MB 1.5 MB/s eta 0:00:07
   ---- ----------------------------------- 1.0/9.8 MB 1.6 MB/s eta 0:00:06
   ------ --------------------------------- 1.6/9.8 MB 1.9 MB/s eta 0:00:05
   -------- ------------------------------- 2.1/9.8 MB 2.1 MB/s eta 0:00:04
   ---------- ----------------------------- 2.6/9.8 MB 2.2 MB/s eta 0:00:04
   ------------- -------------------------- 3.4/9.8 MB 2.4 MB/s eta 0:00:03
   ---------------- ----------------------- 3.9/9.8 MB 2.5 MB/s eta 0:00:03
   ------------------- -------------------- 4.7/9.8 MB 2.6 MB/s eta 0:00:02
   -------------------- ------------------- 5.0/9.8 MB 2.7 MB/s eta 0:00:02
   ---------------------- ----------------- 5.5/9.8 MB 2.5 MB/s eta 0:00:02
   ------------------------ --------------- 6.0/9.8 MB 2.5 MB/s eta 0:00:02
   --------------------------- ------------ 6.8/9.8 MB 2.5 MB/s eta 0:00:02
   ----------------------------- ---------- 7.3/9.8 MB 2.5 MB/s eta 0:00:01
   -------------------------------- ------- 7.9/9.8 MB 2.6 MB/s eta 0:00:01
   ------------------------------------ --- 8.9/9.8 MB 2.7 MB/s eta 0:00:01
   -------------------------------------- - 9.4/9.8 MB 2.7 MB/s eta 0:00:01
   ---------------------------------------  9.7/9.8 MB 2.7 MB/s eta 0:00:01
   ---------------------------------------- 9.8/9.8 MB 2.5 MB/s  0:00:03
Installing collected packages: pandas
Successfully installed pandas-3.0.6
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.2 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [8]:
import pandas as pd

df = pd.read_csv(
    "../data/evenements-publics-openagenda.csv",
    sep=";"
)

df.head()

,Identifiant,Slug,URL canonique,Titre,Description,Description longue,Détail des conditions,Mots clés,Image,Crédits image,...,Agenda d'origine (uid),Contributeur: Email,Contributeur: Téléphone,Contributeur: Nom,Contributeur: Fonction,Contributeur: organisation,Catégorie,Nom du pays,Registration,Liens additionnels
0,55322880,cyberviolences-resister-collectivement-a-la-si...,https://openagenda.com/coolturalia/events/cybe...,Cyberviolences – résister collectivement à la ...,"Qu’est-ce que les cyberviolences, comment se m...",NaN,Gratuit,NaN,NaN,NaN,...,73437356.0,NaN,NaN,NaN,NaN,NaN,NaN,Suisse,NaN,NaN
1,12413663,centre-social-st-rambert-dalbon-5148959,https://openagenda.com/tootsweet/events/centre...,Centre social St Rambert d'Albon,organisé par Centre social St Rambert d'Albon,"<p>Atelier de danses ""Folk""</p>\n<p></p>\n<p>A...",Gratuit,"breton,bretone,danse,atelier,26",NaN,NaN,...,82566953.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,75551745,coupe-de-normandie-vtt-25-septembre-2021,https://openagenda.com/tootsweet/events/coupe-...,Coupe de Normandie VTT - 25 septembre 2021 - F...,Coupe de Normandie et Trophée Régional des Jeu...,<p>L'association Vélo Jeunes Aventure organise...,pass sanitaire obligatoire,"sport,vtt,feuguerolles bully,calvados",https://cibul.s3.amazonaws.com/60a782a88d1e433...,NaN,...,94552197.0,NaN,NaN,NaN,NaN,NaN,NaN,France (Métropole),"[{""type"": ""link"", ""value"": ""http://www.normand...",NaN
3,87153658,un-deux-trad-invite-les-tralala-lovers-8266071,https://openagenda.com/tootsweet/events/un-deu...,"Un, deux, trad invite les Tralala Lovers",avec Tralala Lovers et Viendez-Voir,"<p>Le ""fameux"" bal de Mirecourt est enfin de r...",10€,"baltrad,balfolk,danse,chant,musique,88",https://cibul.s3.amazonaws.com/07ad84a33c24458...,NaN,...,82566953.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"[{""data"": {""author_url"": ""https://www.youtube...."
4,35021962,totalement-90-6588587,https://openagenda.com/tootsweet/events/totale...,Totalement 90,"WORLDS APART, LARUSSO, INDRA, BORIS, YANNICK E...",<p>Totalement 90 accueillera le chanteur Boris...,Tarifs: de 35€ à 45€,"chanson,spectacle,show,Longjumeau,Essonne,Ile ...",https://cibul.s3.amazonaws.com/9f486cc452114f1...,NaN,...,15004001.0,NaN,NaN,NaN,NaN,NaN,NaN,France (Métropole),"[{""type"": ""phone"", ""value"": ""01 69 09 09 09""}]",NaN

In [10]:
df.shape

(124601, 56)

In [11]:
df.columns.tolist()

['Identifiant',
 'Slug',
 'URL canonique',
 'Titre',
 'Description',
 'Description longue',
 'Détail des conditions',
 'Mots clés',
 'Image',
 'Crédits image',
 'Aperçu',
 'Image source',
 'Dernière mise à jour',
 'Résumé horaires',
 'Première date - Début',
 'Première date - Fin',
 'Dernière date - Début',
 'Dernière date - Fin',
 'Horaires détaillés',
 "Code d'accessibilité",
 'Accessibilité',
 'Identifiant du lieu',
 'Coordonnées géographiques',
 'Nom du lieu',
 'Adresse',
 'Arrondissement',
 'Code INSEE',
 'Code postal',
 'Ville',
 'Département',
 'Région',
 'Pays',
 'Image du lieu',
 "Crédits de l'image du lieu",
 'Téléphone du lieu',
 'Site web du lieu',
 'Liens du lieu',
 'Tags du lieu',
 'Description du lieu',
 'Accès / Itinéraire',
 'Événement physique ou en ligne',
 "Lien d'accès en ligne",
 "État de l'événement",
 'Age minimum',
 'Age maximum',
 "Agenda d'origine (titre)",
 "Agenda d'origine (uid)",
 'Contributeur: Email',
 'Contributeur: Téléphone',
 'Contributeur: Nom',
 'Contributeur: Fonction',
 'Contributeur: organisation',
 'Catégorie',
 'Nom du pays',
 'Registration',
 'Liens additionnels']

In [12]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 124601 entries, 0 to 124600
Data columns (total 56 columns):
 #   Column                          Non-Null Count   Dtype
---  ------                          --------------   -----
 0   Identifiant                     124601 non-null  int64
 1   Slug                            124601 non-null  str
 2   URL canonique                   124601 non-null  str
 3   Titre                           123191 non-null  str
 4   Description                     123172 non-null  str
 5   Description longue              111896 non-null  str
 6   Détail des conditions           69532 non-null   str
 7   Mots clés                       62597 non-null   str
 8   Image                           106975 non-null  str
 9   Crédits image                   47918 non-null   str
 10  Aperçu                          106972 non-null  str
 11  Image source                    106972 non-null  str
 12  Dernière mise à jour            124601 non-null  str
 13  Résumé horaires                 124601 non-null  str
 14  Première date - Début           124570 non-null  str
 15  Première date - Fin             124569 non-null  str
 16  Dernière date - Début           124571 non-null  str
 17  Dernière date - Fin             124570 non-null  str
 18  Horaires détaillés              124601 non-null  str
 19  Code d'accessibilité            29860 non-null   str
 20  Accessibilité                   29860 non-null   str
 21  Identifiant du lieu             124304 non-null  float64
 22  Coordonnées géographiques       124177 non-null  str
 23  Nom du lieu                     124304 non-null  str
 24  Adresse                         124260 non-null  str
 25  Arrondissement                  39103 non-null   str
 26  Code INSEE                      95283 non-null   str
 27  Code postal                     114416 non-null  str
 28  Ville                           118219 non-null  str
 29  Département                     113265 non-null  str
 30  Région                          115981 non-null  str
 31  Pays                            122215 non-null  str
 32  Image du lieu                   24412 non-null   str
 33  Crédits de l'image du lieu      17841 non-null   str
 34  Téléphone du lieu               30101 non-null   str
 35  Site web du lieu                29811 non-null   str
 36  Liens du lieu                   10897 non-null   str
 37  Tags du lieu                    23866 non-null   str
 38  Description du lieu             28901 non-null   str
 39  Accès / Itinéraire              17305 non-null   str
 40  Événement physique ou en ligne  124580 non-null  str
 41  Lien d'accès en ligne           1721 non-null    str
 42  État de l'événement             124601 non-null  str
 43  Age minimum                     20767 non-null   float64
 44  Age maximum                     28700 non-null   float64
 45  Agenda d'origine (titre)        123575 non-null  str
 46  Agenda d'origine (uid)          123575 non-null  float64
 47  Contributeur: Email             0 non-null       float64
 48  Contributeur: Téléphone         0 non-null       float64
 49  Contributeur: Nom               0 non-null       float64
 50  Contributeur: Fonction          0 non-null       float64
 51  Contributeur: organisation      0 non-null       float64
 52  Catégorie                       0 non-null       float64
 53  Nom du pays                     122182 non-null  str
 54  Registration                    72178 non-null   str
 55  Liens additionnels              14231 non-null   str
dtypes: float64(10), int64(1), str(45)
memory usage: 53.2 MB

In [13]:
df.isnull().sum().sort_values(ascending=False)

Contributeur: organisation        124601
Contributeur: Téléphone           124601
Contributeur: Email               124601
Contributeur: Fonction            124601
Contributeur: Nom                 124601
Catégorie                         124601
Lien d'accès en ligne             122880
Liens du lieu                     113704
Liens additionnels                110370
Accès / Itinéraire                107296
Crédits de l'image du lieu        106760
Age minimum                       103834
Tags du lieu                      100735
Image du lieu                     100189
Age maximum                        95901
Description du lieu                95700
Site web du lieu                   94790
Code d'accessibilité               94741
Accessibilité                      94741
Téléphone du lieu                  94500
Arrondissement                     85498
Crédits image                      76683
Mots clés                          62004
Détail des conditions              55069
Registration                       52423
Code INSEE                         29318
Aperçu                             17629
Image source                       17629
Image                              17626
Description longue                 12705
Département                        11336
Code postal                        10185
Région                              8620
Ville                               6382
Nom du pays                         2419
Pays                                2386
Description                         1429
Titre                               1410
Agenda d'origine (titre)            1026
Agenda d'origine (uid)              1026
Coordonnées géographiques            424
Adresse                              341
Identifiant du lieu                  297
Nom du lieu                          297
Première date - Fin                   32
Première date - Début                 31
Dernière date - Fin                   31
Dernière date - Début                 30
Événement physique ou en ligne        21
Dernière mise à jour                   0
Horaires détaillés                     0
Slug                                   0
Identifiant                            0
URL canonique                          0
Résumé horaires                        0
État de l'événement                    0
dtype: int64

In [15]:
for i, col in enumerate(df.columns):
    print(f"{i} - {col}")

0 - Identifiant
1 - Slug
2 - URL canonique
3 - Titre
4 - Description
5 - Description longue
6 - Détail des conditions
7 - Mots clés
8 - Image
9 - Crédits image
10 - Aperçu
11 - Image source
12 - Dernière mise à jour
13 - Résumé horaires
14 - Première date - Début
15 - Première date - Fin
16 - Dernière date - Début
17 - Dernière date - Fin
18 - Horaires détaillés
19 - Code d'accessibilité
20 - Accessibilité
21 - Identifiant du lieu
22 - Coordonnées géographiques
23 - Nom du lieu
24 - Adresse
25 - Arrondissement
26 - Code INSEE
27 - Code postal
28 - Ville
29 - Département
30 - Région
31 - Pays
32 - Image du lieu
33 - Crédits de l'image du lieu
34 - Téléphone du lieu
35 - Site web du lieu
36 - Liens du lieu
37 - Tags du lieu
38 - Description du lieu
39 - Accès / Itinéraire
40 - Événement physique ou en ligne
41 - Lien d'accès en ligne
42 - État de l'événement
43 - Age minimum
44 - Age maximum
45 - Agenda d'origine (titre)
46 - Agenda d'origine (uid)
47 - Contributeur: Email
48 - Contributeur: Téléphone
49 - Contributeur: Nom
50 - Contributeur: Fonction
51 - Contributeur: organisation
52 - Catégorie
53 - Nom du pays
54 - Registration
55 - Liens additionnels

In [16]:
[col for col in df.columns if "ville" in col.lower()]

['Ville']

In [17]:
[col for col in df.columns if "région" in col.lower()]

['Région']

In [18]:
[col for col in df.columns if "depart" in col.lower()]

[]

In [19]:
[col for col in df.columns if "pays" in col.lower()]

['Pays', 'Nom du pays']

In [20]:
df["Région"].value_counts().head(20)

Région
Île-de-France                 21477
Nouvelle-Aquitaine            12316
Occitanie                     12240
Hauts-de-France               10829
Provence-Alpes-Côte d'Azur     8556
Auvergne-Rhône-Alpes           8349
Pays de la Loire               7726
Grand Est                      7278
Bretagne                       6217
Normandie                      6001
Centre-Val de Loire            5688
Bourgogne-Franche-Comté        3506
Genève                          834
La Réunion                      501
Berlin                          477
Martinique                      465
Corse                           349
Ile-de-France                   329
Occitania                       285
Guadeloupe                      234
Name: count, dtype: int64

In [21]:
df["Première date - Début"].head()

0    2026-11-26T19:00:00+01:00
1    2021-05-25T19:00:00+02:00
2    2021-09-25T10:00:00+02:00
3    2021-11-06T21:00:00+01:00
4    2021-11-18T20:00:00+01:00
Name: Première date - Début, dtype: str

In [22]:
df["Première date - Début"].min()

'2011-02-10T20:30:00+01:00'

In [23]:
df["Première date - Début"].max()

'2035-09-14T20:30:00+02:00'

In [25]:
import requests

url = "https://public.opendatasoft.com/api/explore/v2.1/catalog/datasets/evenements-publics-openagenda/records"

response = requests.get(url)

print(response.status_code)

data = response.json()

print(data.keys())

200
dict_keys(['total_count', 'results'])

In [26]:
print(data["total_count"])

1291200

In [27]:
len(data["results"])

10

In [28]:
data["results"][0]

{'uid': '55322880',
 'slug': 'cyberviolences-resister-collectivement-a-la-silenciation',
 'canonicalurl': 'https://openagenda.com/coolturalia/events/cyberviolences-resister-collectivement-a-la-silenciation',
 'title_fr': 'Cyberviolences\xa0– résister collectivement à la silenciation',
 'description_fr': 'Qu’est-ce que les cyberviolences, comment se manifestent-elles\xa0?',
 'longdescription_fr': None,
 'conditions_fr': 'Gratuit',
 'keywords_fr': None,
 'image': None,
 'imagecredits': None,
 'thumbnail': None,
 'originalimage': None,
 'updatedat': '2026-10-02T08:26:13+00:00',
 'daterange_fr': 'Jeudi 26 novembre, 19h00',
 'firstdate_begin': '2026-11-26T18:00:00+00:00',
 'firstdate_end': '2026-11-26T20:00:00+00:00',
 'lastdate_begin': '2026-11-26T18:00:00+00:00',
 'lastdate_end': '2026-11-26T20:00:00+00:00',
 'timings': '[{"end": "2026-11-26T21:00:00+01:00", "id": "4AH87R", "begin": "2026-11-26T19:00:00+01:00"}]',
 'accessibility': None,
 'accessibility_label_fr': None,
 'location_uid': '80677191',
 'location_coordinates': {'lon': 6.138586, 'lat': 46.201007},
 'location_name': 'Maison des associations socio-politiques',
 'location_address': 'des Savoises 15, 1205 Genève',
 'location_district': None,
 'location_insee': None,
 'location_postalcode': '1205',
 'location_city': 'Genève',
 'location_department': None,
 'location_region': None,
 'location_countrycode': 'CH',
 'location_image': None,
 'location_imagecredits': None,
 'location_phone': '+41 22 329 20 22',
 'location_website': 'http://www.lafea.org',
 'location_links': None,
 'location_tags': None,
 'location_description_fr': 'http://www.ville-geneve.ch/plan-ville/social/maison-associations-socio-politiques/',
 'location_access_fr': None,
 'attendancemode': '{"id": 1, "label": {"fr": "Sur place", "en": "In situ", "it": "In presenza", "es": "Desconnectad", "de": "Offline", "br": "War al lec\\u2019h", "io": "crwdns14266:0crwdne14266:0", "oc": "Sus pla\\u00e7a", "nl": "Ter plaatse"}}',
 'onlineaccesslink': None,
 'status': '{"id": 1, "label": {"fr": "Programm\\u00e9", "en": "Scheduled", "io": "crwdns16100:0crwdne16100:0", "es": "Programado", "oc": "Programat", "nl": "Gepland", "br": "Raktreset"}}',
 'age_min': None,
 'age_max': None,
 'originagenda_title': 'Ville de Genève - événements organisés par des organisations externes à la Ville de Genève',
 'originagenda_uid': '73437356',
 'contributor_email': None,
 'contributor_contactnumber': None,
 'contributor_contactname': None,
 'contributor_contactposition': None,
 'contributor_organization': None,
 'category': None,
 'country_fr': 'Suisse',
 'registration': None,
 'links': None}

In [29]:
event = data["results"][0]

for key in sorted(event.keys()):
    print(key)

accessibility
accessibility_label_fr
age_max
age_min
attendancemode
canonicalurl
category
conditions_fr
contributor_contactname
contributor_contactnumber
contributor_contactposition
contributor_email
contributor_organization
country_fr
daterange_fr
description_fr
firstdate_begin
firstdate_end
image
imagecredits
keywords_fr
lastdate_begin
lastdate_end
links
location_access_fr
location_address
location_city
location_coordinates
location_countrycode
location_department
location_description_fr
location_district
location_image
location_imagecredits
location_insee
location_links
location_name
location_phone
location_postalcode
location_region
location_tags
location_uid
location_website
longdescription_fr
onlineaccesslink
originagenda_title
originagenda_uid
originalimage
registration
slug
status
thumbnail
timings
title_fr
uid
updatedat

In [30]:
event = data["results"][0]

for key in event.keys():
    if "region" in key.lower():
        print(key)

location_region

In [31]:
for key in event.keys():
    if "city" in key.lower():
        print(key)

location_city

In [32]:
for key in event.keys():
    if "location" in key.lower():
        print(key)

location_uid
location_coordinates
location_name
location_address
location_district
location_insee
location_postalcode
location_city
location_department
location_region
location_countrycode
location_image
location_imagecredits
location_phone
location_website
location_links
location_tags
location_description_fr
location_access_fr

In [33]:
data["results"][0]["location_region"]

In [34]:
data["results"][0]["location_city"]

'Genève'

In [35]:
event = data["results"][0]

print("Ville :", event.get("location_city"))
print("Région :", event.get("location_region"))
print("Pays :", event.get("country_fr"))

Ville : Genève
Région : None
Pays : Suisse

In [47]:
import requests
import pandas as pd

url = "https://public.opendatasoft.com/api/explore/v2.1/catalog/datasets/evenements-publics-openagenda/records"

response = requests.get(
    url,
    params={"limit": 100}
)

data = response.json()

df_api = pd.DataFrame(data["results"])

In [48]:
df_api.shape

(100, 56)

In [50]:
df_api["country_fr"].value_counts(dropna=False)

country_fr
France (Métropole)    95
NaN                    2
Mexique                1
Palestine              1
Guyane Française       1
Name: count, dtype: int64

In [51]:
df_api["location_region"].value_counts(dropna=False).head(20)

location_region
Île-de-France                 23
Provence-Alpes-Côte d'Azur    16
Centre-Val de Loire           13
Bretagne                       7
Auvergne-Rhône-Alpes           6
Pays de la Loire               6
Grand Est                      6
Normandie                      5
Nouvelle-Aquitaine             5
Hauts-de-France                4
NaN                            3
Bourgogne-Franche-Comté        2
Occitanie                      2
Sonora                         1
Guyane                         1
Name: count, dtype: int64

In [41]:
params = {
    "limit": 10,
    "where": "location_region='Île-de-France'"
}

In [42]:
print(response.status_code)
print(len(data["results"]))

200
100

In [43]:
len(data["results"])

100

In [44]:
data["results"][0]["location_region"]

In [52]:
df_api.shape

(100, 56)

In [53]:
df_api.head(1)

,uid,slug,canonicalurl,title_fr,description_fr,longdescription_fr,conditions_fr,keywords_fr,image,imagecredits,...,originagenda_uid,contributor_email,contributor_contactnumber,contributor_contactname,contributor_contactposition,contributor_organization,category,country_fr,registration,links
0,12413663,centre-social-st-rambert-dalbon-5148959,https://openagenda.com/tootsweet/events/centre...,Centre social St Rambert d'Albon,organisé par Centre social St Rambert d'Albon,"<p>Atelier de danses ""Folk""</p>\n<p></p>\n<p>A...",Gratuit,"[breton, bretone, danse, atelier, 26]",NaN,NaN,...,82566953,None,None,None,None,None,None,NaN,NaN,NaN

In [55]:
import pandas as pd

df_raw = pd.read_csv(
    "../data/events_raw.csv"
)

df_raw.shape

(5000, 56)

In [2]:
import pandas as pd

df_raw = pd.read_csv(
    "../data/events_raw.csv"
)

df_raw.shape

(10000, 56)

In [3]:
df_raw.columns.tolist()

['uid',
 'slug',
 'canonicalurl',
 'title_fr',
 'description_fr',
 'longdescription_fr',
 'conditions_fr',
 'keywords_fr',
 'image',
 'imagecredits',
 'thumbnail',
 'originalimage',
 'updatedat',
 'daterange_fr',
 'firstdate_begin',
 'firstdate_end',
 'lastdate_begin',
 'lastdate_end',
 'timings',
 'accessibility',
 'accessibility_label_fr',
 'location_uid',
 'location_coordinates',
 'location_name',
 'location_address',
 'location_district',
 'location_insee',
 'location_postalcode',
 'location_city',
 'location_department',
 'location_region',
 'location_countrycode',
 'location_image',
 'location_imagecredits',
 'location_phone',
 'location_website',
 'location_links',
 'location_tags',
 'location_description_fr',
 'location_access_fr',
 'attendancemode',
 'onlineaccesslink',
 'status',
 'age_min',
 'age_max',
 'originagenda_title',
 'originagenda_uid',
 'contributor_email',
 'contributor_contactnumber',
 'contributor_contactname',
 'contributor_contactposition',
 'contributor_organization',
 'category',
 'country_fr',
 'registration',
 'links']

In [4]:
import pandas as pd

df = pd.read_csv("../data/events_filtered.csv")

df.shape

(1357, 11)

In [5]:
df.head()

,uid,title_fr,description_fr,keywords_fr,firstdate_begin,location_name,location_address,location_city,location_department,location_region,category
0,16655488,Nicolas Giraud PULSE Feat Jorge Vistel,"19h30 & 21h30Nicolas Giraud présente PULSE, un...","['Afrobeat', 'Jazz']",2026-01-02 18:30:00+00:00,JASS CLUB PARIS,"141 Rue de Tolbiac, PARIS",PARIS,Paris,Île-de-France,NaN
1,19237741,Ludivine Issambourg Quintet invite Philippe Se...,19h30 & 21h30Ludivine Issambourg Quintet rasse...,"['Groove', 'Jazz']",2026-01-24 18:30:00+00:00,JASS CLUB PARIS,"141 Rue de Tolbiac, PARIS",PARIS,Paris,Île-de-France,NaN
2,62447525,Tribute to Tony Allen / Nicolas Giraud Feat Jo...,19h30 & 21h30Nicolas Giraud et PULSE se tourne...,"['Afrobeat', 'Jazz']",2026-01-03 18:30:00+00:00,JASS CLUB PARIS,"141 Rue de Tolbiac, PARIS",PARIS,Paris,Île-de-France,NaN
3,78434636,JOB DATING - Le Grand Hôtel Doré *** et le Gra...,"Dans le cadre de la semaine du Tourisme, Franc...","['La semaine du Tourisme', 'Recrutement']",2026-02-05 13:00:00+00:00,Agence Paris 11eme Beaumarchais,75011 Paris,Paris,Paris,Île-de-France,NaN
4,76064548,"Restitution ★ Festival de ""Cane"" de la Halle d...",Projection des travaux des ateliers de cinéma ...,"['CLAVIM', 'La Halle des Épinettes', 'ciné des...",2026-06-28 13:00:00+00:00,La Halle des Épinettes,45-47 rue de l’Egalité 92130 Issy-les-Moulineaux,Issy-les-Moulineaux,Hauts-de-Seine,Île-de-France,NaN